## ETL Strategy for Dataset Handling

Our approach to handling datasets involves employing the Extract, Transform, Load (ETL) strategy. The ETL process consists of three key steps: extraction, loading, and transformation. These steps enable us to effectively manage and prepare datasets for analysis.

### Extraction
In the extraction phase, we retrieve the datasets from various repositories. These repositories may include online databases, file systems, or other sources. By extracting the datasets, we ensure that the necessary data is obtained and made available for further processing.

### Loading
Once the datasets are extracted, we proceed with the loading phase. During this step, the extracted data is loaded into our system, making it accessible for subsequent transformations and analysis. Loading the data ensures that it is readily available in a suitable format for further processing.

### Transformation
The transformation phase is a critical step in the ETL process. Here, we apply a range of operations to convert the raw data into a desired form for analysis. This includes tasks such as data cleaning, filtering, aggregating, and feature engineering. By transforming the data, we enhance its quality, consistency, and usability, enabling us to derive meaningful insights during analysis.

By employing the ETL strategy, we streamline the handling of datasets. This approach allows us to extract relevant data, load it into our system, and transform it into a structured and refined format. This process ultimately facilitates efficient analysis and empowers us to make informed decisions based on the transformed data.

Using the ETL strategy, we ensure that datasets are effectively managed, processed, and transformed, enabling us to derive valuable insights and drive impactful outcomes.

The dataframe df_example with the following structure is what we need:

In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
import os

patient_ids = ['Patient1', 'Patient2', 'Patient3', 'Patient4']
feature_names = ['Feature1', 'Feature2', 'Feature3', 'Feature4']

data = np.random.randint(0, 100, size=(len(patient_ids), len(feature_names)))

df_example = pd.DataFrame(data, columns=feature_names)
df_example.insert(0, 'Patient ID', patient_ids)

df_example

  Patient ID  Feature1  Feature2  Feature3  Feature4
0   Patient1        95        36        44        61
1   Patient2         9        15        94        99
2   Patient3         9        20        19        81
3   Patient4        37        40        65        16

## Clinic data set

**Translation and Protection of the Original Metadata**

The original metadata is written in Turkish and has been expertly translated into English by Dr. [Ozlem Altay](https://scholar.google.com/citations?user=z2bPX2YAAAAJ&hl=en). The original metadata includes sensitive information, such as patients' names, birthdays, and other related data.

To access the original data, we kindly request that you contact the principal investigator, Prof. [Adil Mardinoglu](https://sysmedicine.com/people/).

In [2]:
df_Clinic_v1_raw = pd.read_excel('../AD baseline/Supplementary Table 1.xlsx', sheet_name='Clinic_v1_raw')
df_Clinic_v1_raw.head()

,Patient ID,ADAS group,ADAS-COG,SEX,Age,Cigarette,HB,HCT,RBC,WBC,...,HbA1c,TSH,Diastolic blood pressure (mmHg),Sistolic blood pressure (mmHg),Pulse (beats per minute),Waist circumference (cm),Hip circumference (cm),Weight,Height,BMI
0,TR10001,Medium,18.3,1,64,0,13.6,40.0,4.75,7.32,...,5.58,1.58,79.0,141.0,58.0,106.0,112.0,76.0,170.0,26.30
1,TR10002,High,32.0,0,73,0,11.2,33.7,3.92,5.70,...,5.19,3.02,70.0,120.0,67.0,79.0,93.0,50.6,152.0,21.60
2,TR10004,High,36.0,1,80,0,11.9,36.3,4.42,8.43,...,6.85,2.65,80.0,140.0,72.0,142.0,150.0,135.0,170.0,46.71
3,TR10005,High,39.3,0,61,0,13.1,38.5,4.76,5.28,...,5.79,2.17,68.0,125.0,65.0,74.0,94.0,60.0,159.0,23.70
4,TR10006,Medium,29.0,0,68,0,13.0,35.7,4.21,5.67,...,6.08,3.57,80.0,130.0,74.0,87.0,101.0,61.0,149.0,27.40

In [3]:
df_Clinic_v1_imputed = df_Clinic_v1_raw.copy()
columns_with_missing = df_Clinic_v1_imputed.columns[2:]
imputer = KNNImputer(n_neighbors=10)
df_Clinic_v1_imputed[columns_with_missing] = imputer.fit_transform(df_Clinic_v1_imputed[columns_with_missing])
df_Clinic_v1_imputed.head()

,Patient ID,ADAS group,ADAS-COG,SEX,Age,Cigarette,HB,HCT,RBC,WBC,...,HbA1c,TSH,Diastolic blood pressure (mmHg),Sistolic blood pressure (mmHg),Pulse (beats per minute),Waist circumference (cm),Hip circumference (cm),Weight,Height,BMI
0,TR10001,Medium,18.3,1.0,64.0,0.0,13.6,40.0,4.75,7.32,...,5.58,1.58,79.0,141.0,58.0,106.0,112.0,76.0,170.0,26.30
1,TR10002,High,32.0,0.0,73.0,0.0,11.2,33.7,3.92,5.70,...,5.19,3.02,70.0,120.0,67.0,79.0,93.0,50.6,152.0,21.60
2,TR10004,High,36.0,1.0,80.0,0.0,11.9,36.3,4.42,8.43,...,6.85,2.65,80.0,140.0,72.0,142.0,150.0,135.0,170.0,46.71
3,TR10005,High,39.3,0.0,61.0,0.0,13.1,38.5,4.76,5.28,...,5.79,2.17,68.0,125.0,65.0,74.0,94.0,60.0,159.0,23.70
4,TR10006,Medium,29.0,0.0,68.0,0.0,13.0,35.7,4.21,5.67,...,6.08,3.57,80.0,130.0,74.0,87.0,101.0,61.0,149.0,27.40

Run this cell only once, as it creates a new sheet. After the first run, comment out or disable this cell to prevent duplicate sheets.

In [4]:
# with pd.ExcelWriter("../AD baseline/Supplementary Table 1.xlsx", engine='openpyxl', mode='a') as writer:
#     df_Clinic_v1_imputed.to_excel(writer, sheet_name='Clinic_v1_imputed', index=False)

In [5]:
df_Clinic_v3 = pd.read_excel('../AD baseline/Supplementary Table 1.xlsx', sheet_name='Clinic_v3')
df_Clinic_v3.head()

,Patient ID,Group,ADAS-COG,HB,HCT,RBC,WBC,Platelet,Neutrophil%,Lymphocyte%,...,HbA1c,TSH,Diastolic blood pressure (mmHg),Sistolic blood pressure (mmHg),Pulse (beats per minute),Waist circumference (cm),Hip circumference (cm),Weight,Height,BMI
0,TR10001,Placebo,12.9,14.3,41.4,4.91,9.07,224,72.9,17.0,...,4.87,1.76,56.0,115.0,60.0,106,112,77.0,170,26.60
1,TR10002,Active,31.0,11.1,34.9,3.99,5.73,73,43.5,45.0,...,5.42,7.21,76.9,135.2,71.5,75,92,50.1,152,21.60
2,TR10006,Active,20.3,11.0,32.0,3.94,6.26,217,50.9,37.4,...,5.57,3.29,75.0,131.7,72.0,87,100,55.4,149,24.77
3,TR10008,Placebo,24.3,14.6,42.6,4.79,5.72,237,56.1,31.3,...,5.79,6.37,60.0,120.0,68.0,80,89,42.2,140,21.43
4,TR10011,Active,13.9,12.8,36.5,4.57,6.58,124,71.6,19.9,...,5.26,0.67,75.0,125.0,84.0,90,104,57.3,147,26.38

## Proteomics data set

In [6]:
df_Proteomics_v1 = pd.read_excel('../AD baseline/Supplementary Table 2.xlsx', sheet_name='Proteomics_v1')
df_Proteomics_v1.head()

,Patient ID,AARSD1-ONC,ABHD14B-NEURO,ABL1-ONC,ACAA1-ONC,ACAN-CARDIO,ACE2-CARDIO,ACOX1-CARDIO,ACP5-CARDIO,ACP6-ONC,...,WNT9A-INF,WWP2-NEURO,XCL1-ONC,XG-CARDIO,XPNPEP2-ONC,XRCC4-NEURO,YES1-ONC,YTHDF3-INF,ZBTB16-ONC,ZBTB17-CARDIO
0,TR10001,3.348122,2.089108,0.413531,-0.156888,-0.336284,0.634362,-0.607463,-0.700799,0.620113,...,-0.145817,-0.989140,0.140783,0.545180,0.114860,-0.846528,0.481248,1.176901,-0.468632,0.451749
1,TR10002,1.867629,0.604588,0.166621,-0.820185,0.089733,-0.769731,-1.213938,-0.370926,0.324367,...,0.291190,-1.686025,-0.508594,0.897293,-0.827149,-0.992737,-0.108829,-0.071031,-0.716202,-0.130863
2,TR10004,2.043374,0.890614,0.335164,0.955768,-0.337980,-0.156509,-1.592354,-0.008296,0.299340,...,-0.393919,-1.580078,0.582005,1.227334,-1.591022,-0.665404,0.339130,-0.666462,-0.563579,-0.052376
3,TR10005,2.121647,0.896753,-0.047804,0.914253,0.066355,-0.783626,-0.862757,0.642352,-2.156880,...,-0.283300,-1.440843,0.727752,0.982803,-0.267838,-0.779878,0.357967,-0.208829,-0.953239,0.203797
4,TR10006,2.229805,1.502206,0.465384,1.007255,0.382988,-0.850165,-1.564609,-0.238950,0.917961,...,0.552320,-1.525864,1.169178,2.142708,-1.042898,-0.205235,0.140026,1.571458,-0.369312,-0.060027

In [7]:
df_Proteomics_v3 = pd.read_excel('../AD baseline/Supplementary Table 2.xlsx', sheet_name='Proteomics_v3')
df_Proteomics_v3.head()

,Patient ID,AARSD1-ONC,ABHD14B-NEURO,ABL1-ONC,ACAA1-ONC,ACAN-CARDIO,ACE2-CARDIO,ACOX1-CARDIO,ACP5-CARDIO,ACP6-ONC,...,WNT9A-INF,WWP2-NEURO,XCL1-ONC,XG-CARDIO,XPNPEP2-ONC,XRCC4-NEURO,YES1-ONC,YTHDF3-INF,ZBTB16-ONC,ZBTB17-CARDIO
0,TR10001,3.403780,1.954592,0.149687,-0.374987,-0.324092,0.634871,-0.594473,-0.719953,0.545059,...,0.070097,-1.236139,0.350656,0.288101,0.383849,-0.539426,0.148474,-0.184703,-0.729049,0.215074
1,TR10002,2.426317,0.607488,0.225091,-2.149980,-0.633627,-0.995883,-1.378625,-0.152694,0.138859,...,0.054550,-0.512743,-0.538830,0.850920,-1.678234,-0.576932,0.472165,0.182950,-0.292153,-0.019914
2,TR10006,2.120553,1.644887,0.326469,0.562881,0.367600,-1.020961,-0.063415,0.062838,0.662100,...,-0.189368,-1.741376,0.764948,3.003235,-1.562236,-0.169876,-0.215365,1.488423,-0.343728,-0.015285
3,TR10008,2.268989,0.753291,0.086812,-0.018470,-0.502894,-0.628509,-0.981348,-0.417524,-1.199021,...,-0.519135,-1.548927,-0.157078,0.298956,1.503269,-0.944317,0.388690,0.170695,-0.995061,0.499459
4,TR10011,1.565321,0.493535,-0.072906,-0.573269,0.137744,-1.036323,-1.094877,0.421928,0.365690,...,-0.365510,-1.580571,0.509686,1.145627,-0.959005,-0.942768,0.402153,1.249869,-0.909813,-0.371575

## Metabolomics data set

In [8]:
df_Metabolomics_annotation = pd.read_excel('../AD baseline/Supplementary Table 3.xlsx', sheet_name='Chemical Annotation')
df_Metabolomics_annotation = df_Metabolomics_annotation[['CHEM_ID', 'CHEMICAL_NAME', 'SUPER_PATHWAY', 'SUB_PATHWAY']]
df_Metabolomics_annotation.head()

,CHEM_ID,CHEMICAL_NAME,SUPER_PATHWAY,SUB_PATHWAY
0,35,S-1-pyrroline-5-carboxylate,Amino Acid,Glutamate Metabolism
1,50,spermidine,Amino Acid,Polyamine Metabolism
2,55,1-methylnicotinamide,Cofactors and Vitamins,Nicotinate and Nicotinamide Metabolism
3,62,"12,13-DiHOME",Lipid,"Fatty Acid, Dihydroxy"
4,71,5-hydroxyindoleacetate,Amino Acid,Tryptophan Metabolism

In [9]:
df_Metabolomics_raw_v1 = pd.read_excel('../AD baseline/Supplementary Table 3.xlsx', sheet_name='Raw data v1')
df_Metabolomics_raw_v1.head()

,Patient ID,35,50,55,62,71,93,98,111,112,...,100022007,100022008,100022009,100022013,100022014,100022015,100022041,100022120,100022127,100022172
0,TR10001,1.876385,1.499106,1.412571,0.136451,1.797723,0.908777,1.494606,0.782101,1.703375,...,2.454370,3.669768,3.412437,3.867799,2.588726,4.218116,1.323448,1.803960,1.346314,10.742700
1,TR10002,0.870135,0.335634,0.697246,0.136451,0.803716,1.021230,0.637586,0.103553,0.861881,...,1.727515,1.865731,1.830065,0.412587,2.529860,2.948811,1.024573,0.989108,0.376000,2.004696
2,TR10004,1.219075,0.547764,1.086736,0.389284,1.041555,1.287757,1.570575,1.115286,1.232927,...,1.768236,1.701329,1.579306,2.199696,3.072884,3.578556,1.406634,0.525013,1.238615,4.576278
3,TR10005,0.601068,1.066200,1.000000,0.289884,0.741918,1.286097,0.841365,0.103553,0.842491,...,2.282074,2.101596,1.996074,0.930567,2.629732,2.724775,1.009459,1.088842,0.513293,0.600721
4,TR10006,1.366418,0.497218,0.535672,0.136451,0.781970,1.007700,1.213698,0.647549,0.906098,...,1.755832,1.071725,1.044726,1.704031,1.282638,1.355934,1.670262,0.936448,1.385892,3.653871

In [10]:
column_mapping = dict(zip(df_Metabolomics_annotation['CHEM_ID'], df_Metabolomics_annotation['CHEMICAL_NAME']))
df_Metabolomics_v1 = df_Metabolomics_raw_v1.rename(columns=column_mapping)
df_Metabolomics_v1.head()

,Patient ID,S-1-pyrroline-5-carboxylate,spermidine,1-methylnicotinamide,"12,13-DiHOME",5-hydroxyindoleacetate,alpha-ketoglutarate,kynurenate,3-hydroxyisobutyrate,3-hydroxy-3-methylglutarate,...,"bilirubin degradation product, C17H18N2O4 (3)**","bilirubin degradation product, C17H20N2O5 (1)**","bilirubin degradation product, C17H20N2O5 (2)**",tetrahydrocortisol glucuronide,"bilirubin degradation product, C16H18N2O5 (3)**","bilirubin degradation product, C16H18N2O5 (4)**","N,N-dimethyl-pro-pro",oxindolylalanine,tetrahydrocortisone glucuronide (5),perfluorohexanesulfonate (PFHxS)
0,TR10001,1.876385,1.499106,1.412571,0.136451,1.797723,0.908777,1.494606,0.782101,1.703375,...,2.454370,3.669768,3.412437,3.867799,2.588726,4.218116,1.323448,1.803960,1.346314,10.742700
1,TR10002,0.870135,0.335634,0.697246,0.136451,0.803716,1.021230,0.637586,0.103553,0.861881,...,1.727515,1.865731,1.830065,0.412587,2.529860,2.948811,1.024573,0.989108,0.376000,2.004696
2,TR10004,1.219075,0.547764,1.086736,0.389284,1.041555,1.287757,1.570575,1.115286,1.232927,...,1.768236,1.701329,1.579306,2.199696,3.072884,3.578556,1.406634,0.525013,1.238615,4.576278
3,TR10005,0.601068,1.066200,1.000000,0.289884,0.741918,1.286097,0.841365,0.103553,0.842491,...,2.282074,2.101596,1.996074,0.930567,2.629732,2.724775,1.009459,1.088842,0.513293,0.600721
4,TR10006,1.366418,0.497218,0.535672,0.136451,0.781970,1.007700,1.213698,0.647549,0.906098,...,1.755832,1.071725,1.044726,1.704031,1.282638,1.355934,1.670262,0.936448,1.385892,3.653871

Run this cell only once, as it creates a new sheet. After the first run, comment out or disable this cell to prevent duplicate sheets.

In [11]:
# with pd.ExcelWriter("../AD baseline/Supplementary Table 3.xlsx", engine='openpyxl', mode='a') as writer:
#     df_Metabolomics_v1.to_excel(writer, sheet_name='Metabolomics_v1', index=False)

In [12]:
df_Metabolomics_v3 = pd.read_excel('../AD baseline/Supplementary Table 3.xlsx', sheet_name='Metabolomics_v3')
df_Metabolomics_v3.head()

,Patient ID,S-1-pyrroline-5-carboxylate,spermidine,1-methylnicotinamide,"12,13-DiHOME",5-hydroxyindoleacetate,alpha-ketoglutarate,kynurenate,3-hydroxyisobutyrate,3-hydroxy-3-methylglutarate,...,"bilirubin degradation product, C17H18N2O4 (3)**","bilirubin degradation product, C17H20N2O5 (1)**","bilirubin degradation product, C17H20N2O5 (2)**",tetrahydrocortisol glucuronide,"bilirubin degradation product, C16H18N2O5 (3)**","bilirubin degradation product, C16H18N2O5 (4)**","N,N-dimethyl-pro-pro",oxindolylalanine,tetrahydrocortisone glucuronide (5),perfluorohexanesulfonate (PFHxS)
0,TR10001,1.435783,0.882287,0.776708,0.136451,1.794188,1.063585,2.009061,0.898666,1.635809,...,1.998036,4.475786,4.271959,3.556774,2.627187,4.763583,1.378735,1.396068,1.131437,11.034843
1,TR10002,1.618681,0.455134,29.182345,0.738428,0.405946,1.280356,0.361462,2.464256,0.787285,...,2.383356,3.381262,3.186799,0.538257,2.549841,3.208121,0.776730,1.238734,0.421742,2.346026
2,TR10006,1.747661,0.739505,0.706667,1.023036,0.961085,1.019811,1.109185,1.291325,0.994409,...,2.073654,2.223929,2.066035,2.115674,1.559717,1.596558,1.609755,0.738210,1.682293,4.073656
3,TR10008,1.361268,0.417946,0.224903,0.136451,1.122181,0.761883,0.817736,0.655750,0.811047,...,1.408897,1.162300,1.207621,3.204922,1.003358,0.996653,1.515019,0.617126,2.281504,9.355035
4,TR10011,0.764711,0.776656,3.254177,0.136451,1.016975,0.808186,0.666856,0.599713,0.797388,...,1.211207,1.962523,1.929925,2.169843,1.587407,1.651783,1.117903,0.680069,1.414228,1.150886

## Gut metagenomics data set

In [13]:
arr = os.listdir('../AD gut metaphlan 4/')

try:
    arr.remove('.DS_Store')
except:
    pass

arr.sort()

df_gut = pd.DataFrame([], columns = ['X.clade_name'])

for i in range(0, len(arr)):
    temp = pd.read_excel('../AD gut metaphlan 4/' + arr[i])
    temp = temp.rename(columns = {'#clade_name':'X.clade_name'})
    df_gut = df_gut.merge(temp, on = "X.clade_name", how = 'outer')
    df_gut = df_gut.rename(columns = {'relative_abundance': arr[i].split('_')[1]})
    
droprows = []
for i in range(0, len(df_gut)):
    if df_gut['X.clade_name'][i].split('|')[-1][0] != 's' or df_gut['X.clade_name'][i].split('|')[0].split('__')[-1] != 'Bacteria':
        droprows.append(i)
df_gut = df_gut.drop(droprows)
df_gut = df_gut.reset_index(drop=True)

df_gut = df_gut[df_gut.isnull().sum(axis=1) < 0.8*(df_gut.shape[1]-1)]
df_gut = df_gut.reset_index(drop=True)
df_gut = df_gut.fillna(0)

temp = df_gut.set_index('X.clade_name').T.reset_index()
temp.columns.name = None
temp = temp.rename(columns={"index": "Patient ID"})
for item in list(temp.columns):
    temp = temp.rename(columns={item: item.split('|')[-1].split('__')[-1]})
df_gut_v1 = temp.copy()
df_gut_v1.head()

,Patient ID,Bacteroides_uniformis,Collinsella_aerofaciens,Clostridium_sp_AF15_49,Eubacterium_rectale,Blautia_wexlerae,Bilophila_wadsworthia,Blautia_sp_AF19_10LB,Fusicatenibacter_saccharivorans,Phocaeicola_vulgatus,...,GGB9291_SGB14248,Mitsuokella_jalaludinii,Clostridium_SGB4751,Prevotella_sp_885,Holdemanella_biformis,Clostridia_unclassified_SGB3983,GGB4750_SGB6579,GGB9687_SGB15191,GGB9631_SGB15087,Senegalimassilia_faecalis
0,TR10001,0.95778,0.04355,0.13831,1.75240,1.63963,0.05469,1.20515,2.52749,12.12145,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TR10002,2.00536,0.94489,0.33112,0.02925,0.26896,0.55387,0.12181,0.48199,5.17690,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TR10004,0.11030,11.05348,0.00000,0.25988,0.31249,0.29458,0.00000,0.52771,0.43339,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,TR10005,0.65023,0.39225,0.00000,0.15288,0.66535,0.26426,0.36313,0.23698,10.86928,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TR10006,5.43565,1.11656,0.00000,3.99766,0.57139,0.41074,0.12876,2.45223,4.48492,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Run this cell only once, as it creates a new sheet. After the first run, comment out or disable this cell to prevent duplicate sheets.

In [14]:
# with pd.ExcelWriter("../AD baseline/Supplementary Table 4.xlsx", engine='openpyxl', mode='a') as writer:
#     df_gut_v1.to_excel(writer, sheet_name='Gut_Metagenomics_v1', index=False)

In [15]:
df_gut_v3 = pd.read_excel('../AD baseline/Supplementary Table 4.xlsx', sheet_name='Gut_Metagenomics_v3')
df_gut_v3.head()

,Patient ID,Bacteroides_uniformis,Collinsella_aerofaciens,Clostridium_sp_AF15_49,Eubacterium_rectale,Blautia_wexlerae,Bilophila_wadsworthia,Blautia_sp_AF19_10LB,Fusicatenibacter_saccharivorans,Phocaeicola_vulgatus,...,GGB9291_SGB14248,Mitsuokella_jalaludinii,Clostridium_SGB4751,Prevotella_sp_885,Holdemanella_biformis,Clostridia_unclassified_SGB3983,GGB4750_SGB6579,GGB9687_SGB15191,GGB9631_SGB15087,Senegalimassilia_faecalis
0,TR10001,0.53640,0.70613,0.00000,1.54003,3.16972,0.00989,1.67784,5.76745,5.81777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TR10002,2.72952,0.35999,0.39898,0.00644,0.19802,0.51546,0.11388,0.25201,8.83548,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TR10006,2.52521,0.07298,0.43194,5.22688,0.70210,0.33662,0.11202,1.16199,8.52549,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,TR10011,0.00000,0.00000,0.00000,0.00000,4.14958,0.00000,0.00000,0.00000,0.00493,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TR10013,1.47662,0.26996,0.00000,0.35630,0.39160,0.12231,0.01748,0.49879,0.14556,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Saliva metagenomics data set

In [16]:
arr = os.listdir('../AD saliva metaphlan/')

try:
    arr.remove('.DS_Store')
except:
    pass

N = len(arr)

arr.sort()

df_saliva = pd.DataFrame([], columns = ['X.clade_name'])

for i in range(0, len(arr)):
    temp = pd.read_excel('../AD saliva metaphlan/' + arr[i])
    temp = temp.rename(columns = {'#clade_name':'X.clade_name'})
    df_saliva = df_saliva.merge(temp, on = "X.clade_name", how = 'outer')
    df_saliva = df_saliva.rename(columns = {'relative_abundance': arr[i].split('_')[1]})
    
droprows = []
for i in range(0, len(df_saliva)):
    if df_saliva['X.clade_name'][i].split('|')[-1][0] != 's' or df_saliva['X.clade_name'][i].split('|')[0].split('__')[-1] != 'Bacteria':
        droprows.append(i)
df_saliva = df_saliva.drop(droprows)
df_saliva = df_saliva.reset_index(drop=True)

df_saliva = df_saliva[df_saliva.isnull().sum(axis=1) < 0.8*(df_saliva.shape[1]-1)]
df_saliva = df_saliva.reset_index(drop=True)
df_saliva = df_saliva.fillna(0)

temp = df_saliva.set_index('X.clade_name').T.reset_index()
temp.columns.name = None
temp = temp.rename(columns={"index": "Patient ID"})
for item in list(temp.columns):
    temp = temp.rename(columns={item: item.split('|')[-1].split('__')[-1]})
df_saliva_v1 = temp.copy()
df_saliva_v1.head()

,Patient ID,Neisseria_subflava,Prevotella_jejuni,Veillonella_dispar,Bacteroidaceae_unclassified_SGB1468,Actinomyces_graevenitzii,Prevotella_melaninogenica,Megasphaera_micronuciformis,Candidatus_Saccharibacteria_unclassified_SGB19850,Veillonella_atypica,...,Cryptobacterium_curtum,Mitsuokella_sp_oral_taxon_131,Aggregatibacter_aphrophilus,Porphyromonas_SGB2042,Limosilactobacillus_fermentum,GGB1025_SGB1319,Scardovia_wiggsiae,Olsenella_profusa,GGB12785_SGB19823,GGB4964_SGB6927
0,TR10001,13.74380,6.96770,6.12494,5.35304,3.75767,3.57818,3.55098,3.27253,3.12112,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,TR10002,10.80154,1.30653,0.88840,0.68495,0.08464,4.77892,0.25528,1.52136,1.06870,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,TR10004,0.26505,8.53173,4.45193,3.54639,0.83725,7.08564,3.01372,0.21499,4.26255,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,TR10005,11.47228,0.33038,2.68498,2.23840,0.47341,11.83875,0.49085,0.60705,1.00110,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TR10006,17.99029,0.60793,0.31396,1.03930,0.02424,4.67914,0.41281,0.52077,0.91449,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Run this cell only once, as it creates a new sheet. After the first run, comment out or disable this cell to prevent duplicate sheets.

In [17]:
# with pd.ExcelWriter("../AD baseline/Supplementary Table 5.xlsx", engine='openpyxl', mode='a') as writer:
#     df_saliva_v1.to_excel(writer, sheet_name='Saliva_Metagenomics_v1', index=False)

In [18]:
df_saliva_v3 = pd.read_excel('../AD baseline/Supplementary Table 5.xlsx', sheet_name='Saliva_Metagenomics_v3')
df_saliva_v3.head()

,Patient ID,Neisseria_subflava,Prevotella_jejuni,Veillonella_dispar,Bacteroidaceae_unclassified_SGB1468,Actinomyces_graevenitzii,Prevotella_melaninogenica,Megasphaera_micronuciformis,Candidatus_Saccharibacteria_unclassified_SGB19850,Veillonella_atypica,...,Cryptobacterium_curtum,Mitsuokella_sp_oral_taxon_131,Aggregatibacter_aphrophilus,Porphyromonas_SGB2042,Limosilactobacillus_fermentum,GGB1025_SGB1319,Scardovia_wiggsiae,Olsenella_profusa,GGB12785_SGB19823,GGB4964_SGB6927
0,TR10001,5.58390,0.75234,0.40199,12.70928,7.70900,0.46736,1.99330,0.84936,0.68183,...,0.0,0.0,0.0000,0.0,0.0,0.0,0.04361,0.00000,0.0,0.00000
1,TR10002,2.88735,2.38678,4.20802,6.53640,0.25600,3.80325,0.95008,2.45942,3.12593,...,0.0,0.0,0.0000,0.0,0.0,0.0,0.00000,0.00000,0.0,0.00000
2,TR10008,9.39713,7.31923,1.80370,2.96838,0.12355,9.18801,1.35171,2.59998,6.58612,...,0.0,0.0,0.2736,0.0,0.0,0.0,0.00000,0.00000,0.0,0.01516
3,TR10011,8.39100,1.46305,0.00000,1.54145,0.00000,3.72486,0.11413,0.12265,0.93081,...,0.0,0.0,0.0000,0.0,0.0,0.0,0.00000,0.00000,0.0,0.00000
4,TR10013,32.38788,0.03518,0.06917,1.74994,1.04176,0.34849,0.21344,0.41456,0.18532,...,0.0,0.0,0.0000,0.0,0.0,0.0,0.01874,0.01769,0.0,0.00000